### PR TITLE
WIP: 283.virtue sso

### PR DESCRIPTION
**Pull request by lilk-bit**
Added resource home mounts (container isolated) to mount resources to where dockers will have access.

### CODE REVIEW

**Comment by fpatwa** [comment]
How has this been tested?
I would suggest building containers in the CI Environment first and then using them to verify. This can be done with the Jenkins Job:
http://35.170.157.4:8080/view/all/job/docker-virtue/

**Comment by lilk-bit** [comment]
> How has this been tested?
> I would suggest building containers in the CI Environment first and then using them to verify. This can be done with the Jenkins Job:
> http://35.170.157.4:8080/view/all/job/docker-virtue/

I was testing it manually. I didn't realize there was a jenkins test for it.

**Review by fpatwa — APPROVED** [review]
I am fine with this as long as this has been locally tested to at least ensure that the containers build.
Also before running the Jenkins job to deploy these to production, I would recommend they be deployed and tested using the CI ECR.

**Comment by lilk-bit** [comment]
> I am fine with this as long as this has been locally tested to at least ensure that the containers build.
> Also before running the Jenkins job to deploy these to production, I would recommend they be deployed and tested using the CI ECR.

Can you explain this to me? I haven't working on the docker-virtue repo before this and this is sounding more complicated.

**Comment by fpatwa** [comment]
> > I am fine with this as long as this has been locally tested to at least ensure that the containers build.
> > Also before running the Jenkins job to deploy these to production, I would recommend they be deployed and tested using the CI ECR.
> 
> Can you explain this to me? I haven't working on the docker-virtue repo before this and this is sounding more complicated.

So there are 2 Docker registries - one is a one we use for CI and the other is production which is hardcoded in our code. So if we rebuild the container and deploy to production and there is an issue it breaks all of our stacks since the containers are downloaded from the same place anytime a new role is created. If we deploy to CI, then potentially we can login to the virtue and pull down the docker image and test it using the CI endpoint of the docker registry - essentially do a manual role create or we can even just modify code on  a particular stack to test this out. It would be a code change for:
https://github.com/starlab-io/docker-virtue/blob/master/virtue/virtue-base/Dockerfile.virtuebase#L1
change:
`starlab-virtue`
to
`starlab-virtue-ci`
I would ask Jonathan or Alex for help with this also.

**Comment by fpatwa** [comment]
> > How has this been tested?
> > I would suggest building containers in the CI Environment first and then using them to verify. This can be done with the Jenkins Job:
> > http://35.170.157.4:8080/view/all/job/docker-virtue/
> 
> I was testing it manually. I didn't realize there was a jenkins test for it.

The Jenkins Job is not to test it but to deploy it to the docker registry.

**Pull request merged**
